### ISSUE TITLE
fs-uae-2.8.1 version bump + suggestions

### ISSUE THREAD

**Issue by ghost** [netfab/overlay#1]
Just a friendly reminder for telling you that fs-uae-2.8.1 is out.

I just renamed your ebuilds and modified them in my personal local overlay:

1. I added python-3.5 support to `python-lhafile-0.2.1.ebuild` and `fs-uae-launcher-2.8.1.ebuild` by editing the `PYTHON_COMPAT` variable
2. I replaced http with https in both the `HOMEPAGE` and `SRC_URI` variables in all three ebuilds

**Comment by netfab** [comment]
Forgot to push 2.8.0 ebuilds, thanks for your updates.
