### ISSUE TITLE
"!!! Section 'netfab' in repos.conf has name different from repository name 'netfab-overlay' set inside repository"

### ISSUE THREAD

**Issue by Sophira** [netfab/overlay#7]
Hi,

I'm not sure if this affects use of the repository or not, but when I synced my layman repositories today I started getting warnings from emerge:

    !!! Section 'netfab' in repos.conf has name different from repository name 'netfab-overlay' set inside repository

I assume this is because `layman` only knows this repository as `netfab` but the recent rename of the overlay changed how the repo knows itself.

I assume this is as simple as changing the name in `repos.conf` (and any atoms that refer to it by name) but I figured you'd want to know about this!

**Comment by netfab** [comment]
Yes, fixing the name in repos.conf should do it. I also got that error one month ago.
After fixing it, subsequent sync should be fine. Please let me know if this is not the case.
Thanks.

**Comment by Sophira** [comment]
It's fine now, yes... it might be something you want to get in contact with the people who maintain the layman repository list about, though, since all new additions of the repo via layman will still have this issue.

**Comment by netfab** [comment]
Sorry, I do not use layman. I do not see how a commit in my repo can influence the behavior of an external software. If my repo is listed in the layman repository list (who? where?), it was not added by me.

**Comment by Sophira** [comment]
Ah, no, you're right, my apologies! It appears I added your repository manually and it isn't actually part of the repositories list.

I deeply apologise for the confusion! This was my responsibility after all and I didn't need to open this issue after all. Thank you for your help, though!

**Comment by netfab** [comment]
No problem. Closing this then.
